from psychopy import visual, event, core
from psychopy.visual import ShapeStim
import time
win = visual.Window(fullscr=bool, units='height', color = (-0.3,0,-0.7))
#circle left
circle1 = visual.Circle(win, radius=0.25, edges=60, fillColor=(1, 0, -1), lineColor = [1, -0.5, -1], lineColorSpace= "rgb", lineWidth=2.5)
circle1.pos = (-0.20,0)
shadow1 = visual.Circle(win, radius=0.2, edges=32, fillColor=(1, -1, -1), lineColor = [1, 0, -1], lineColorSpace= "rgb", lineWidth=1.5, opacity = 0.2)
shadow1.pos = (-0.175,0)
#circle middle small
circle2 = visual.Circle(win, radius=0.297, edges=60, fillColor=(1, 0, -1), lineColor = [1, 0, -1], lineColorSpace= "rgb", lineWidth=1)
circle2.pos = (0,0)
shadow3 = visual.Circle(win, radius=0.25, edges=60, fillColor=(1, -1, -1), lineColor = [1, 0, -1], lineColorSpace= "rgb", lineWidth=1, opacity = 0.2)
shadow3.pos = (0,0)
#Circle middle big
circle3 = visual.Circle(win, radius=0.30, edges=60, fillColor=(1, 0, -1), lineColor = [1, -0.5, -1], lineColorSpace= "rgb", lineWidth=2.5)
circle3.pos = (0,0)
#Circle right
circle4 = visual.Circle(win, radius=0.25, edges=60, fillColor=(1, 0, -1), lineColor = [1, -0.5, -1], lineColorSpace= "rgb", lineWidth=2.5)
circle4.pos = (0.2,0)
shadow4 = visual.Circle(win, radius=0.2, edges=32, fillColor=(1, -1, -1), lineColor = [1, 0, -1], lineColorSpace= "rgb", lineWidth=1.5, opacity = 0.2)
shadow4.pos = (0.175,0)
#triangle left
triangle1 = visual.Polygon(win, edges=3, radius=0.075, pos=(-0.12,0.10), lineColor=[1, -0.5, -1], fillColor=(1, -0.5, -1))
triangleshadow1 = visual.Polygon(win, edges=3, radius=0.055, pos=(-0.101,0.09), lineColor=[1, -0.5, -1], fillColor=(-1,-1,-1), opacity =0.75)
#triangle right
triangle2 = visual.Polygon(win, edges=3, radius=0.075, pos=(0.12,0.10), lineColor=[1, -0.5, -1], fillColor=(1, -0.5, -1))
triangleshadow2 = visual.Polygon(win, edges=3, radius=0.055, pos=(0.139,0.09), lineColor=[1, -0.5, -1], fillColor=(-1,-1,-1), opacity =0.75)
#copy mouth
mouth1 = visual.Circle(win, radius=0.17, edges=60, fillColor=(-1,-1,-1), lineColor = [1, -0.5, -1], lineColorSpace= "rgb", lineWidth=7.5, opacity = 0.90)
mouth1.pos = (0,0.01)
mouth2 = visual.Circle(win, radius=0.17, edges=60, fillColor=(1, 0, -1), lineColor = [1, 0, -1], lineColorSpace= "rgb", lineWidth=1.5)
mouth2.pos = (0,0.065)
# tooth left
tooth1 = visual.Polygon(win, edges=3, radius= -0.035, pos=(-0.034,-0.11), lineColor=[1, -0.2, -1], fillColor=(1, -0.2, -1))
# tooth right
tooth2 = visual.Polygon(win, edges=3, radius= 0.035, pos=(0.032,-0.16), lineColor=[1, -0.2, -1], fillColor=(1, -0.2, -1))
# stock 
stock = visual.Polygon(win, ori = 70, edges=4, radius= 0.050, pos=(0.055,0.315), lineColor=[1, -0.5, -1], fillColor=(1, -0.5, -1))
stockcircle = visual.Circle(win, ori = 70, radius= 0.0355, pos=(0.067,0.342), lineColor=[1, -0.5, -1], fillColor=(1, -0.5, -1))
#text
txt = visual.TextStim(win, text = "Happy Halloween!", color = (1, -0.5, -1),pos = (-0.39,-0.35), height = 0.14)
#draw
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
txt.draw()
# 1
win.flip()
core.wait(1)
# 2
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
win.flip()
core.wait(0.5)
#3
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
txt.draw()
win.flip()
core.wait(0.5)
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
win.flip()
core.wait(0.5)
#3
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
txt.draw()
win.flip()
core.wait(0.5)
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
win.flip()
core.wait(0.5)
#3
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
txt.draw()
win.flip()
core.wait(0.5)
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
win.flip()
core.wait(0.5)
#3
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
txt.draw()
win.flip()
core.wait(0.5)
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
win.flip()
core.wait(0.5)
#3
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
txt.draw()
win.flip()
core.wait(0.5)
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
win.flip()
core.wait(0.5)
#3
stock.draw()
stockcircle.draw()
circle3.draw()
circle1.draw()
shadow1.draw()
circle4.draw()
shadow4.draw()
circle2.draw()
mouth1.draw()
mouth2.draw()
shadow3.draw()
triangle1.draw()
triangleshadow1.draw()
triangle2.draw()
triangleshadow2.draw()
tooth1.draw()
tooth2.draw()
txt.draw()
win.flip()
core.wait(0.5)

