#import
from psychopy import visual
import time
from psychopy.visual import ShapeStim
#win
win = visual.Window(fullscr=True, color=[-0.5,-0.5,-0.5])
#achtergrond
halloween_picture = "halloweenachtergrond.png"
picture = visual.ImageStim(win, image = halloween_picture, size=(2, 2))
picture.draw()
#vorm
cirkelmiddenomtrek = visual.Circle(win, radius=0.5, edges=30, color='black')
cirkelmidden = visual.Circle(win, radius=0.45, edges=30, color='darkorange')
cirkellinksomtrek= visual.Circle(win, radius=0.45, edges=30, color='black', pos=(-0.2, 0))
cirkellinks = visual.Circle(win, radius=0.4, edges=30, color='darkorange', pos=(-0.2, 0))
cirkelrechtsomtrek = visual.Circle(win, radius=0.45, edges=30, color='black', pos=(0.2, 0))
cirkelrechts = visual.Circle(win, radius=0.4, edges=30, color='darkorange', pos=(0.2, 0))
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
#steelt
steeltjeomtrek = visual.Rect(win, width=0.08, height=0.19, color='black', pos=(0,0.59))
steeltje = visual.Rect(win, width=0.05, height=0.2, color = 'DarkGreen', pos=(0,0.55))
steeltjeomtrek.draw()
steeltje.draw()
#ogen
LoogVert = [(0.0,0.5),(0.09,0.18),(0.39,0.31),(0.19,0.04),(0.49,-0.11),(0.16,-0.12),(0.22,-0.45),(0.0,-0.2),(-0.22,-0.45),(-0.16,-0.12),(-0.49,-0.11),(-0.19,0.04),(-0.39,0.31),(-0.09,0.18)]
Loog = ShapeStim(win, vertices=LoogVert, fillColor='yellow', lineWidth=4, lineColor='black', size=(0.2, 0.2), pos=(-0.2, 0.2))
RoogVert = [(0.0,0.5),(0.09,0.18),(0.39,0.31),(0.19,0.04),(0.49,-0.11),(0.16,-0.12),(0.22,-0.45),(0.0,-0.2),(-0.22,-0.45),(-0.16,-0.12),(-0.49,-0.11),(-0.19,0.04),(-0.39,0.31),(-0.09,0.18)]
Roog = ShapeStim(win, vertices=RoogVert, fillColor='yellow', lineWidth=4, lineColor='black', size=(0.2, 0.2), pos=(0.2, 0.2))
Roog.draw()
Loog.draw()
#neus
neusomtrek = visual.Polygon(win, edges=3, radius=0.57, color='black', size=(0.1,0.1), pos=(0,0.05))
neus = visual.Polygon(win, edges=3, radius=0.5, color='yellow', size=(0.1, 0.1), pos=(0, 0.05))
neusomtrek.draw()
neus.draw()
#mond en tanden
mondomtrek = visual.Rect(win, width=0.44, height=0.24, lineColor= 'black', fillColor='black', pos=(0, -0.2))
mond = visual.Rect(win, width=0.40, height=0.20, lineWidth=2, lineColor='yellow', fillColor=[1.0, 1.0, -1], pos=(0, -0.2))
tand1 = visual.Rect(win, width=0.05, height=0.1, fillColor='darkorange', lineColor='darkorange', pos=(-0.15, -0.14))
tand2 = visual.Rect(win, width=0.05, height=0.1, fillColor='darkorange', lineColor='darkorange', pos=(-0.05, -0.14))
tand3 = visual.Rect(win, width=0.05, height=0.1, fillColor='darkorange', lineColor='darkorange', pos=(0.05, -0.14))
tand4 = visual.Rect(win, width=0.05, height=0.1, fillColor='darkorange', lineColor='darkorange', pos=(0.15, -0.14))
tand5 = visual.Rect(win, width=0.05, height=0.1, fillColor='darkorange', lineColor='darkorange', pos=(-0.1, -0.26))
tand6 = visual.Rect(win, width=0.05, height=0.1, fillColor='darkorange', lineColor='darkorange', pos=(0, -0.26))
tand7 = visual.Rect(win, width=0.05, height=0.1, fillColor='darkorange', lineColor='darkorange', pos=(0.1, -0.26))
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
#tekst
tekstbovenaan = visual.TextStim(win, text = "Happy", color="darkred", pos=(-0.5, 0.8), height=0.2)
tekstonderaan = visual.TextStim(win, text = "Halloween!", color="darkred", pos=(0.5, -0.8), height=0.2)
tekstbovenaan.draw()
tekstonderaan.draw()
#opening window: figuur + tekst
win.flip()
time.sleep(1)
#enkel figuur
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
win.flip()
time.sleep(0.5)
#figuur + tekst
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
tekstbovenaan.draw()
tekstonderaan.draw()
win.flip()
time.sleep(1)
#enkel figuur
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
win.flip()
time.sleep(0.5)
#figuur + tekst
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
tekstbovenaan.draw()
tekstonderaan.draw()
win.flip()
time.sleep(1)
#enkel figuur
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
win.flip()
time.sleep(0.5)
#figuur + tekst
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
tekstbovenaan.draw()
tekstonderaan.draw()
win.flip()
time.sleep(1)
#enkel figuur
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
win.flip()
time.sleep(0.5)
#figuur + tekst
picture.draw()
cirkelmiddenomtrek.draw()
cirkelrechtsomtrek.draw()
cirkellinksomtrek.draw()
cirkellinks.draw()
cirkelrechts.draw()
cirkelmidden.draw()
steeltjeomtrek.draw()
steeltje.draw()
Roog.draw()
Loog.draw()
neusomtrek.draw()
neus.draw()
mond.draw()
tand1.draw()
tand2.draw()
tand3.draw()
tand4.draw()
tand5.draw()
tand6.draw()
tand7.draw()
tekstbovenaan.draw()
tekstonderaan.draw()
win.flip()
time.sleep(1)
win.close()