from psychopy import visual
import time
import turtle
win=visual.Window(size=[600,600])

# Esther: je zou alle vormen een eigen naam kunnen geven, die hier aanmaken maar zonder ze al te drawen.
# Esther: eens alles is aangemaakt, kan je de vormen tekenen en je scherm flippen.
# Esther: voor de volgende presentatie hoef je de vormen dat niet meer opnieuw aan te maken, te hoeft enkel te drawen en flippen.
polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,-0.6))
stim.draw()
win.flip()
time.sleep(1)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
win.flip()
time.sleep(0.5)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,-0.6))
stim.draw()
win.flip()
time.sleep(1)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
win.flip()
time.sleep(0.5)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,-0.6))
stim.draw()
win.flip()
time.sleep(1)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
win.flip()
time.sleep(0.5)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,-0.6))
stim.draw()
win.flip()
time.sleep(1)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
win.flip()
time.sleep(0.5)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,-0.6))
stim.draw()
win.flip()
time.sleep(1)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
win.flip()
time.sleep(0.5)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,-0.6))
stim.draw()
win.flip()
time.sleep(1)

polygon=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
polygon.draw()
circle =visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
triangle.draw()
circle=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
circle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
triangle.draw()
triangle=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
triangle.draw()
win.flip()
time.sleep(0.5)

win.close()
