from psychopy import visual 
from psychopy.visual import ShapeStim
import time
win = visual.Window( size = [600,400])
pumpkin = visual.Polygon(win, edges= 4000,color = 'orange')
eyeleft = visual.Polygon(win,edges=4, radius=0.1, color ='black',pos=(-0.25,0.14))
eyeright = visual.Polygon(win, edges=4, radius=0.1, fillColor='black', lineColor= 'orange', pos=(0.25,0.14))
SmileVert = [(-.2,.25),(-.2,.2),(-.15,0),(0,0),(.6,0),(.65,.1),(0.65,0.25)]
Smile = ShapeStim(win, vertices=SmileVert, fillColor='black', lineWidth=0, size=.75, pos=(-.2, -.25))
nose = visual.Polygon(win, vertices=3, color='black', pos=(0,0.07),size=0.12)
msg = visual.TextStim(win, text=u"Happy Halloween!", pos=(0, 0.6))
msg.draw()
pumpkin.draw()
eyeleft.draw()
eyeright.draw()
Smile.draw()
nose.draw()
win.flip()
time.sleep(1)
msg = visual.TextStim(win, text=u"Happy Halloween!", pos=(0, 0.6))
msg.draw()
win.flip()
time.sleep(1/2)
win.flip()
msg = visual.TextStim(win, text=u"Happy Halloween!", pos=(0, 0.6))
msg.draw()
win.flip()
time.sleep(0.5)
win.flip()
msg = visual.TextStim(win, text=u"Happy Halloween!", pos=(0, 0.6))
msg.draw()
win.flip()
time.sleep(0.5)
win.flip()
msg = visual.TextStim(win, text=u"Happy Halloween!", pos=(0, 0.6))
msg.draw()
win.flip()
time.sleep(0.5)
win.flip()
msg = visual.TextStim(win, text=u"Happy Halloween!", pos=(0, 0.6))
msg.draw()
win.flip()
time.sleep(0.5)
win.flip()
msg = visual.TextStim(win, text=u"Happy Halloween!", pos=(0, 0.6))
msg.draw()
win.flip()
time.sleep(0.5)
win.flip()
win.close()