#goal of this code:create my own pumpkin
from psychopy import visual
#visual is a module from psychopy containing several visual methods
import time
#time is a module from python containing several time-related methods
#create the pumpkinshape
win=visual.Window(fullscr=True,color=(-1,-1,-1),monitor="testMonitor",units="norm")
pumpkin=visual.Polygon(win, edges = 500,radius = .60,pos = (0,0),fillColor = 'orange',lineColor='orange',lineWidth=4)
pumpkin.draw()
top=visual.Rect(win, size=0.2,pos = (0,0.635), fillColor = 'brown',lineColor='brown')
top.draw()
top2=visual.Polygon(win, edges = 500,radius = .05,pos = (0,0.7),fillColor = 'brown',lineColor='brown')
top2.draw()
nose=visual.Polygon(win, edges = 3,radius = .07,pos = (0,0.03),ori=180,fillColor = 'black',lineColor='black')
nose.draw()
lefteye=visual.Polygon(win, edges = 3,radius = .1,pos = (-0.2,0.2),fillColor = 'black',lineColor='black')
lefteye.draw()
righteye=visual.Polygon(win, edges = 3,radius = .1,pos = (0.2,0.2),fillColor = 'black',lineColor='black')
righteye.draw()
openmouth=visual.Polygon(win, edges = 500,radius = .15,pos = (0,-0.3),fillColor = 'black',lineColor='black')
openmouth.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'orange',pos=(0,-0.8))
stim.draw()
win.flip()
time.sleep(1)
pumpkin=visual.Polygon(win, edges = 500,radius = .60,pos = (0,0),fillColor = 'orange',lineColor='orange',lineWidth=4)
pumpkin.draw()
top=visual.Rect(win, size=0.2,pos = (0,0.635), fillColor = 'brown',lineColor='brown')
top.draw()
top2=visual.Polygon(win, edges = 500,radius = .05,pos = (0,0.7),fillColor = 'brown',lineColor='brown')
top2.draw()
nose=visual.Polygon(win, edges = 3,radius = .07,pos = (0,0.03),ori=180,fillColor = 'black',lineColor='black')
nose.draw()
lefteye=visual.Polygon(win, edges = 3,radius = .1,pos = (-0.2,0.2),fillColor = 'black',lineColor='black')
lefteye.draw()
righteye=visual.Polygon(win, edges = 3,radius = .1,pos = (0.2,0.2),fillColor = 'black',lineColor='black')
righteye.draw()
openmouth=visual.Polygon(win, edges = 500,radius = .15,pos = (0,-0.3),fillColor = 'black',lineColor='black')
openmouth.draw()
tooth1=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.05,-0.15),ori=180,fillColor = 'orange',lineColor='orange')
tooth1.draw()
tooth2=visual.Polygon(win, edges = 3,radius = .08,pos = (0.05,-0.15),ori=180,fillColor = 'orange',lineColor='orange')
tooth2.draw()
tooth3=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.05,-0.45),fillColor = 'orange',lineColor='orange')
tooth3.draw()
tooth4=visual.Polygon(win, edges = 3,radius = .08,pos = (0.05,-0.45),fillColor = 'orange',lineColor='orange')
tooth4.draw()
stim = visual.TextStim(win, text = "Boo!", color = 'orange',pos=(0,-0.8))
stim.draw()
win.flip()
time.sleep(0.5)
pumpkin=visual.Polygon(win, edges = 500,radius = .60,pos = (0,0),fillColor = 'orange',lineColor='orange',lineWidth=4)
pumpkin.draw()
top=visual.Rect(win, size=0.2,pos = (0,0.635), fillColor = 'brown',lineColor='brown')
top.draw()
top2=visual.Polygon(win, edges = 500,radius = .05,pos = (0,0.7),fillColor = 'brown',lineColor='brown')
top2.draw()
nose=visual.Polygon(win, edges = 3,radius = .07,pos = (0,0.03),ori=180,fillColor = 'black',lineColor='black')
nose.draw()
lefteye=visual.Polygon(win, edges = 3,radius = .1,pos = (-0.2,0.2),fillColor = 'black',lineColor='black')
lefteye.draw()
righteye=visual.Polygon(win, edges = 3,radius = .1,pos = (0.2,0.2),fillColor = 'black',lineColor='black')
righteye.draw()
openmouth=visual.Polygon(win, edges = 500,radius = .15,pos = (0,-0.3),fillColor = 'black',lineColor='black')
openmouth.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'orange',pos=(0,-0.8))
stim.draw()
win.flip()
time.sleep(1)
pumpkin=visual.Polygon(win, edges = 500,radius = .60,pos = (0,0),fillColor = 'orange',lineColor='orange',lineWidth=4)
pumpkin.draw()
top=visual.Rect(win, size=0.2,pos = (0,0.635), fillColor = 'brown',lineColor='brown')
top.draw()
top2=visual.Polygon(win, edges = 500,radius = .05,pos = (0,0.7),fillColor = 'brown',lineColor='brown')
top2.draw()
nose=visual.Polygon(win, edges = 3,radius = .07,pos = (0,0.03),ori=180,fillColor = 'black',lineColor='black')
nose.draw()
lefteye=visual.Polygon(win, edges = 3,radius = .1,pos = (-0.2,0.2),fillColor = 'black',lineColor='black')
lefteye.draw()
righteye=visual.Polygon(win, edges = 3,radius = .1,pos = (0.2,0.2),fillColor = 'black',lineColor='black')
righteye.draw()
openmouth=visual.Polygon(win, edges = 500,radius = .15,pos = (0,-0.3),fillColor = 'black',lineColor='black')
openmouth.draw()
tooth1=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.05,-0.15),ori=180,fillColor = 'orange',lineColor='orange')
tooth1.draw()
tooth2=visual.Polygon(win, edges = 3,radius = .08,pos = (0.05,-0.15),ori=180,fillColor = 'orange',lineColor='orange')
tooth2.draw()
tooth3=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.05,-0.45),fillColor = 'orange',lineColor='orange')
tooth3.draw()
tooth4=visual.Polygon(win, edges = 3,radius = .08,pos = (0.05,-0.45),fillColor = 'orange',lineColor='orange')
tooth4.draw()
stim = visual.TextStim(win, text = "Boo!", color = 'orange',pos=(0,-0.8))
stim.draw()
win.flip()
time.sleep(0.5)
pumpkin=visual.Polygon(win, edges = 500,radius = .60,pos = (0,0),fillColor = 'orange',lineColor='orange',lineWidth=4)
pumpkin.draw()
top=visual.Rect(win, size=0.2,pos = (0,0.635), fillColor = 'brown',lineColor='brown')
top.draw()
top2=visual.Polygon(win, edges = 500,radius = .05,pos = (0,0.7),fillColor = 'brown',lineColor='brown')
top2.draw()
nose=visual.Polygon(win, edges = 3,radius = .07,pos = (0,0.03),ori=180,fillColor = 'black',lineColor='black')
nose.draw()
lefteye=visual.Polygon(win, edges = 3,radius = .1,pos = (-0.2,0.2),fillColor = 'black',lineColor='black')
lefteye.draw()
righteye=visual.Polygon(win, edges = 3,radius = .1,pos = (0.2,0.2),fillColor = 'black',lineColor='black')
righteye.draw()
openmouth=visual.Polygon(win, edges = 500,radius = .15,pos = (0,-0.3),fillColor = 'black',lineColor='black')
openmouth.draw()
tooth1=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.05,-0.15),ori=180,fillColor = 'orange',lineColor='orange')
tooth1.draw()
tooth2=visual.Polygon(win, edges = 3,radius = .08,pos = (0.05,-0.15),ori=180,fillColor = 'orange',lineColor='orange')
tooth2.draw()
tooth3=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.05,-0.45),fillColor = 'orange',lineColor='orange')
tooth3.draw()
tooth4=visual.Polygon(win, edges = 3,radius = .08,pos = (0.05,-0.45),fillColor = 'orange',lineColor='orange')
tooth4.draw()
stim = visual.TextStim(win, text = "Happy Halloween!", color = 'orange',pos=(0,-0.8))
stim.draw()
win.flip()
time.sleep(1)
win.close()
