import time
from psychopy import visual

window = visual.Window(fullscr = True, color = 'black')
Stem = visual.Rect(window, width = 0.05, height = 0.2, color = 'green', pos = [0,0.5])
Stem.draw()
PumpkinMiddle = visual.Polygon (window, 50, size = [0.3, 1], pos = [0,0], color = 'orange')
PumpkinMiddle.draw()
PumpkinL1 = visual.Polygon (window, 50, size = [0.3, 0.9], pos = [-0.15,0], color = 'orange')
PumpkinL1.draw()
PumpkinR1 = visual.Polygon (window, 50, size = [0.3, 0.9], pos = [0.15,0], color = 'orange')
PumpkinR1.draw()
PumpkinL1 = visual.Polygon (window, 50, size = [0.25, 0.8], pos = [-0.25,0], color = 'orange')
PumpkinL1.draw()
PumpkinL1 = visual.Polygon (window, 50, size = [0.25, 0.8], pos = [0.25,0], color = 'orange')
PumpkinL1.draw()
EyeL = visual.Polygon (window, 3, size = [0.15, 0.3], pos = [-0.2, 0.1], color = 'black')
EyeL.draw()
EyeR = visual.Polygon (window, 3, size = [0.15, 0.3], pos = [0.2, 0.1], color = 'black')
EyeR.draw()
PupilL = visual.Polygon (window, 3, size = [0.075, 0.075], pos = [-0.2, 0.04], color = 'orange')
PupilL.draw()
PupilR = visual.Polygon (window, 3, size = [0.075, 0.075], pos = [0.2, 0.04], color = 'orange')
PupilR.draw()
Mouth1 = visual.Polygon (window, 15, size = [0.5, 0.3], pos = [0,-0.22], color = 'black')
Mouth1.draw()
Mouth2 = visual.Polygon (window, 15, size = [0.5, 0.3], pos = [0,-0.25], color = 'orange')
Mouth2.draw()
Text = visual.TextStim(window, 'Happy Halloween!', color = 'orange', pos = [0, -0.6])
Text.draw()
window.flip()
time.sleep(3)
