from psychopy import visual, event
import time
from psychopy.visual import ShapeStim

#zeer leuke en leerrijke taak! Goede manier om bepaalde codes in de vingers te krijgen :) 
#p.s. Ik weet dat er waarschijnlijk een eenvoudigere manier is om de 'flashende tekst'te krijgen, maar die vind ik niet :/ ik weet ook niet goed hoe ik een gebogen lijn kan maken.

win= visual.Window(fullscr=True,color=(-1,-1,-0.8))


Cirkel= visual.Circle(win, radius=0.65,edges= 128, pos= (0,0), closeShape=True, lineColor= 'DarkOrange', fillColor ='orange')
Cirkel.draw()

mondvert= [(0,-0.1),(0.2,0),(0.5,-0.2),(0.3,-0.4),(0.1,-0.35),(0,-0.5),(-0.2,-0.3),(-0.3,-0.4),(-0.55,-0.1),(-0.3,0),(-0.2,-0.1),(-0.1,0)]

oogLvert= [(-0.45,0.38),(-0.1,0.3),(-0.1,0.2),(-0.2,0.1),(-0.3,0.12),(-0.43,0.36)]
linkeroog=ShapeStim(win, vertices=oogLvert, lineColor='Black', fillColor=(-0.6,-1,-1))
linkeroog.draw()

oogRvert= [(0.45,0.38),(0.1,0.3),(0.1,0.2),(0.2,0.1),(0.3,0.12),(0.43,0.36)]
rechteroog=ShapeStim(win,vertices=oogRvert, lineColor='Black', fillColor=(-0.6,-1,-1) )
rechteroog.draw()

mondvert2= [(-0.5,0.3),(-0.4,0),(-.35,0.07),(-0.2,-0.08),(-0.15,0),(0,-0.15),(0.045,-0.1),(0.1,-0.18),(0.3,0.07),(0.34,0),(0.5,0.3),(0.55,0),(0.3,-0.4),(0.2,-0.3),(0,-0.5),(-0.1,-0.3),(-0.2,-0.38),(-0.32,-0.21),(-0.4,-0.3),(-0.55,0)]
mond=ShapeStim(win, vertices=mondvert2, lineColor='Black', fillColor=(-0.6,-1,-1))
mond.draw()

stemvert= [(-0.1,0.64),(-0.03,0.68),(0.07,0.8),(0.18,0.81),(0.16,0.7),(0.12,0.67),(0.15,0.64)]
Stem= ShapeStim(win, vertices=stemvert,lineColor=(-0.8,-0.5,-1), fillColor=(-0.8,-0.5,-1))
Stem.draw()

PsychopyOogL= visual.GratingStim(win, mask='circle', ori=45,sf=4, size= 0.15, pos= (-0.26,0.23))
PsychopyOogL.draw()

PsychopyOogR= visual.GratingStim(win, mask='circle', ori=45,sf=4, size= 0.15, pos= (0.26,0.23))
PsychopyOogR.draw()

PupilLinks= visual.Circle(win, size= 0.09, pos=(-0.26,0.23), lineColor= 'DarkOrange', fillColor='black')
PupilLinks.draw()

PupilRechts= visual.Circle(win, size= 0.09, pos=(0.26,0.23), lineColor= 'DarkOrange', fillColor='black')
PupilRechts.draw()

Neusvert= [(-0.09,0.02),(0,0.22),(0.09,0.02)]
Neus= ShapeStim(win, vertices= Neusvert,lineColor='Black', fillColor=(-0.6,-1,-1))
Neus.draw()

Tekst= visual.TextStim(win, text='Happy Halloween!', color='Orange', pos= (0,-0.84), bold=True, font= 'Old English Text MT', height=0.2)
Tekst.draw()

win.flip()
time.sleep(1)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)
Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)
Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)
Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)
Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)
Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)
Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)
Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()
Tekst.draw()

win.flip()
time.sleep(0.5)

Cirkel.draw()
linkeroog.draw()
rechteroog.draw()
mond.draw()
Stem.draw()
PsychopyOogL.draw()
PsychopyOogR.draw()
PupilLinks.draw()
PupilRechts.draw()
Neus.draw()

Boo= visual.TextStim(win, text= 'Boo!', font= 'Old English Text MT', height= 0.7, pos= (0,0))


while not event.getKeys():
   Tekst.draw()
   Cirkel.setOri(1, '-')
   linkeroog.setOri(1, '-')
   rechteroog.setOri(1, '-')
   mond.setOri(1, '-')
   Stem.setOri(1, '-')
   Neus.setOri(1, '-')
   Cirkel.draw()
   linkeroog.draw()
   rechteroog.draw()
   mond.draw()
   Stem.draw()
   Neus.draw()
   win.flip()


win.close()