from psychopy import visual, core
from psychopy.visual import ShapeStim
import time
#invoegen van de schermen 
win = visual.Window(fullscr= True, units= 'height', color='black')
achtergrondImage= visual.ImageStim(win, 'bliksem.gif', size= [0.4,0.4], pos=( 0.7,0.3))
achtergrondImage2= visual.ImageStim(win, 'webje.jpg', size= [0.4,0.4], pos=( -0.7,0.3))
achtergrondImage3= visual.ImageStim(win, 'vleermuis.png', size= [0.4,0.4], pos=( 0.7,-0.3))
#ovaal pompoen
cirkel= visual.Circle( win, radius=0.30, edges= 20, color= 'orange')
cirkel2= visual.Circle(win, radius=0.30, edges=20, color= 'orange', pos= (0.2,0))
Cirkel3= visual.Circle(win,radius=0.30,edges=20, color= 'orange', pos= (-0.2,0))
#poging steel, 
steel= visual.Rect(win, width=0.04, height= 0.07, color= 'green', pos= (0,0.321))
#ogen 
driehoek= visual.Circle( win, radius= 0.08, edges= 3, color='black')
driehoek2= visual.Circle(win, radius= 0.08, edges=3, color='black', pos= (-0.2,0.15))
driehoek3= visual.Circle(win, radius=0.08, edges=3 , color= 'black', pos= (0.2, 0.15))
# mond
mond1= visual.Circle(win, radius= 0.08, edges=4, color= 'black', pos= (-0.2,-0.15))
mond2= visual.Circle(win, radius= 0.08, edges=4, color= 'black', pos= (-0.10,-0.15))
mond3= visual.Circle(win, radius= 0.08, edges=4, color= 'black', pos= (-0.0,-0.15))
mond4= visual.Circle(win, radius= 0.08, edges=4, color= 'black', pos= (0.10,-0.15))
mond5= visual.Circle(win, radius= 0.08, edges=4, color= 'black', pos= (0.2,-0.15))
#happy Halloween text
stim1 = visual. TextStim( win, text= "Happy Halloween!", color= 'red', pos= (-0.30, -0.35), height= 0.07)

#algemene zaken
cirkel.draw()
cirkel2.draw()
Cirkel3.draw()
steel.draw()
driehoek.draw()
driehoek2.draw()
driehoek3.draw()
mond1.draw()
mond2.draw()
mond3.draw()
mond4.draw()
mond5.draw()
stim1.draw()
achtergrondImage.autoDraw=True
achtergrondImage2.autoDraw=True
achtergrondImage3.autoDraw=True
win.flip()
time.sleep(1)
#afwisselen
cirkel.draw()
cirkel2.draw()
Cirkel3.draw()
steel.draw()
driehoek.draw()
driehoek2.draw()
driehoek3.draw()
mond1.draw()
mond2.draw()
mond3.draw()
mond4.draw()
mond5.draw()
win.flip()
time.sleep(0.5)
#afwisselen
cirkel.draw()
cirkel2.draw()
Cirkel3.draw()
steel.draw()
driehoek.draw()
driehoek2.draw()
driehoek3.draw()
mond1.draw()
mond2.draw()
mond3.draw()
mond4.draw()
mond5.draw()
stim1.draw()
win.flip()
time.sleep(0.5)
#afwisselen
cirkel.draw()
cirkel2.draw()
Cirkel3.draw()
steel.draw()
driehoek.draw()
driehoek2.draw()
driehoek3.draw()
mond1.draw()
mond2.draw()
mond3.draw()
mond4.draw()
mond5.draw()
win.flip()
time.sleep(0.5)
#afwisselen
cirkel.draw()
cirkel2.draw()
Cirkel3.draw()
steel.draw()
driehoek.draw()
driehoek2.draw()
driehoek3.draw()
mond1.draw()
mond2.draw()
mond3.draw()
mond4.draw()
mond5.draw()
stim1.draw()
win.flip()
time.sleep(0.5)

win.close()