from psychopy import visual
import time
win = visual.Window(fullscr=True)
steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
stim = visual.TextStim(win, text = "Happy Halloween", color = 'black', pos= (0, -0.7), font= "Forte", height= 0.2)
stim.draw()
win.flip()
time.sleep(0.5)

# Esther: je maakt hier de window opnieuw aan, maar dat is helemaal niet nodig, die bestaat al ;)
win = visual.Window(fullscr=True)

# Esther: idem voor alle grafische elementen zoals steel, pompoen etc.
# ESther: deze hoef je vanaf hier niet meer opnieuw aan te maken want ze bestaan reeds.
# Esther: het enige wat je hier hoeft te herhalen zijn de .draw(), .flip() en .sleep() commando's.

steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
win.flip()
time.sleep(0.5)
win = visual.Window(fullscr=True)
steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
stim = visual.TextStim(win, text = "Happy Halloween", color = 'black', pos= (0, -0.7), font= "Forte", height= 0.2)
stim.draw()
win.flip()
time.sleep(0.5)
win = visual.Window(fullscr=True)
steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
win.flip()
time.sleep(0.5)
win = visual.Window(fullscr=True)
steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
stim = visual.TextStim(win, text = "Happy Halloween", color = 'black', pos= (0, -0.7), font= "Forte", height= 0.2)
stim.draw()
win.flip()
time.sleep(0.5)
win = visual.Window(fullscr=True)
steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
win.flip()
time.sleep(0.5)
win = visual.Window(fullscr=True)
steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
stim = visual.TextStim(win, text = "Happy Halloween", color = 'black', pos= (0, -0.7), font= "Forte", height= 0.2)
stim.draw()
win.flip()
time.sleep(0.5)
win = visual.Window(fullscr=True)
steel=visual.Rect(win, color="green", width= 0.10, height= 1, pos=(0, 0.2))
steel.draw()
pompoen = visual.Circle(win, color="orange", size=(0.6,1))
pompoen.draw()
pompoen2=visual.Circle(win, color="orange", size=(0.6,1), pos=(-0.12, 0))
pompoen2.draw()
pompoen3=visual.Circle(win, color="orange", size=(0.6,1), pos=(0.12, 0))
pompoen3.draw()
oog1=visual.Polygon(win, edges=3, color="black", size=(0.15, 0.15))
oog1.draw()
oog2=visual.Circle(win, edges=3, color=(-1,-1,-1), size= (0.2,0.2), pos=(-0.1, 0.2))
oog2.draw()
oog3=visual.Polygon(win, edges=3, color="black", size=(0.2,0.2), pos=(0.1,0.2))
oog3.draw()
mond=visual.Polygon(win, edges=3, color="black", size= (0.10, 0.15), pos= (0, -0.25))
mond.draw()
mond2=visual.Polygon(win, edges=3, color= "black", size= (0.10, 0.15), pos= (0.05, -0.25))
mond2.draw()
mond3=visual.Polygon(win, edges=3, color="black", size=(0.10, 0.15), pos=(-0.05, -0.25))
mond3.draw()
win.flip()
time.sleep(0.5)
win.close()
