
from psychopy import visual
import time

win=visual.Window([800,600],fullscr=True)

hoed=visual.Circle(win,radius=0.2, edges=50, fillColor='black',lineColor='black', size=[3,0.25], pos=[0,0.5])
hoed.draw()
hoed1=visual.Polygon(win, edges=3, fillColor='black',lineColor='black', radius=1)
hoed1.draw()

circle=visual.Circle(win, radius=0.5,edges=50, fillColor='orange', lineColor='black',size=[1.75,1])
circle.draw()

linkeroog=visual.Circle(win, radius=0.1, edges=50,fillColor='black', lineColor='black', pos= [-0.25,0.25],size=[1.75,1],ori=25)
linkeroog.draw()
rechteroog=visual.Circle(win, radius=0.1, edges=50,fillColor='black', lineColor='black', pos= [0.25,0.25],size=[1.75,1],ori=335)
rechteroog.draw()
neus=visual.Polygon(win, edges=3, fillColor='black', lineColor='black', radius=0.15)
neus.draw()
mond=visual.Circle(win, radius=0.1, edges=50,fillColor='black',lineColor='black', pos= [0,-0.25],size=[1.5,0.5])
mond.draw()

lijn1=visual.Circle(win, radius=0.40, edges=50, lineColor='black', size=[2,1.25])
lijn1.draw()
lijn2=visual.Circle(win, radius=0.40, edges=50, lineColor='black', size=[1.65,1.25])
lijn2.draw()
lijn3=visual.Circle(win, radius=0.40, edges=50, lineColor='black', size=[1.20,1.25])
lijn3.draw()
lijn4=visual.Circle(win, radius=0.40, edges=50, lineColor='black', size=[0.65,1.25])
lijn4.draw()

# Esther: awesome :D
borstelsteel=visual.Rect(win, width=0.05, height=1.25, lineColor='brown', fillColor='brown', pos=[0,-0.45], ori=315)
borstelsteel.draw()
borstel=visual.Polygon(win, edges=3, radius=0.35, lineColor='yellow', fillColor='yellow', pos=[0.5,-0.95], ori=315)
borstel.draw()

zin=visual.TextStim(win, 'Happy Halloween', color='black',pos=[0,-0.8])
zin.draw()

# Esther: het is al heel goed dat je eerst alle grafische elementen aanmaakt en daarna enkel nog met .draw() werkt.
# Esther: misschien was het net nog een tikje eleganter om nog niet te drawen terwijl je de elementen aan het aanmaken bent, maar dat is een kwestie van smaak ;)

win.flip()
time.sleep(1)

hoed.draw()
hoed1.draw()
circle.draw()
linkeroog.draw()
rechteroog.draw()
neus.draw()
mond.draw()
lijn1.draw()
lijn2.draw()
lijn3.draw()
lijn4.draw()
borstelsteel.draw()
borstel.draw()
win.flip()
time.sleep(0.5)

hoed.draw()
hoed1.draw()
circle.draw()
linkeroog.draw()
rechteroog.draw()
neus.draw()
mond.draw()
lijn1.draw()
lijn2.draw()
lijn3.draw()
lijn4.draw()
borstelsteel.draw()
borstel.draw()
zin.draw()
win.flip()
time.sleep(1)

hoed.draw()
hoed1.draw()
circle.draw()
linkeroog.draw()
rechteroog.draw()
neus.draw()
mond.draw()
lijn1.draw()
lijn2.draw()
lijn3.draw()
lijn4.draw()
borstelsteel.draw()
borstel.draw()
win.flip()
time.sleep(0.5)

hoed.draw()
hoed1.draw()
circle.draw()
linkeroog.draw()
rechteroog.draw()
neus.draw()
mond.draw()
lijn1.draw()
lijn2.draw()
lijn3.draw()
lijn4.draw()
borstelsteel.draw()
borstel.draw()
zin.draw()
win.flip()
time.sleep(1)

hoed.draw()
hoed1.draw()
circle.draw()
linkeroog.draw()
rechteroog.draw()
neus.draw()
mond.draw()
lijn1.draw()
lijn2.draw()
lijn3.draw()
lijn4.draw()
borstelsteel.draw()
borstel.draw()
win.flip()
time.sleep(0.5)

hoed.draw()
hoed1.draw()
circle.draw()
linkeroog.draw()
rechteroog.draw()
neus.draw()
mond.draw()
lijn1.draw()
lijn2.draw()
lijn3.draw()
lijn4.draw()
borstelsteel.draw()
borstel.draw()
zin.draw()
win.flip()
time.sleep(1)

win.close()