from psychopy import visual
import time

win = visual.Window(size=[700,700])

#drawingpumpkin
leftcircle = visual.Circle(win,radius=0.3, pos=(-0.25,0),lineColor='orange',lineColorSpace='rgb', fillColor='orange')
middlecircle = visual.Circle(win,radius=0.3, pos=(0,0),lineColor='orange',lineColorSpace='rgb', fillColor='orange')
rightcircle = visual.Circle(win,radius=0.3, pos=(0.25,0),lineColor='orange',lineColorSpace='rgb', fillColor='orange')

#face
lefteye= visual.ShapeStim(win,lineColor='black',lineColorSpace='rgb', fillColor='black',fillColorSpace='rgb', vertices=((-0.08, 0), (0, 0.1), (0.08, 0)),  pos=(-0.15,0.08))
righteye= visual.ShapeStim(win,lineColor='black',lineColorSpace='rgb', fillColor='black',fillColorSpace='rgb', vertices=((-0.08, 0), (0, 0.1), (0.08, 0)),  pos=(0.15,0.08))
nose= visual.ShapeStim(win,lineColor='black',lineColorSpace='rgb', fillColor='black',fillColorSpace='rgb', vertices=((-0.04, 0), (0, 0.07), (0.04, 0)), pos=(0,0.02))
mouth= visual.ShapeStim(win,lineColor='black',lineColorSpace='rgb', fillColor='black',fillColorSpace='rgb', vertices=((-0.3,0.125), (-0.1, 0), (0, 0.075),(0.1,0),(0.3,0.125),(0.1,-0.1),(0,0),(-0.1,-0.1)), pos=(0,-0.1))


#text
text = visual.TextStim(win,text= "Happy Halloween", pos=(0,0.7), color='orange')

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(1)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()
text.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
mouth.draw()
nose.draw()

win.flip()
time.sleep(0.5)

leftcircle.draw()
rightcircle.draw()
middlecircle.draw()
lefteye.draw()
righteye.draw()
nose.draw()
mouth.draw()
text.draw()

win.flip()
time.sleep(0.5)

win.close()