# Esther: deze library heb je waarschijnlijk overgenomen uit de demos, maar dat is niet meer nodig
# Esther: deze was wel nog nodig bij Python2, maar nu we in Python3 werken doet die er niet meer toe
# Esther: weer een lijntje code minder ;)
#from __future__ import division
import time
# Esther: de modules event en core gebruik je in dit script ook niet, dus hoeven niet ingeladen te worden ;)
from psychopy import visual #, event, core
# Esther: idem voor het lijntje code hieronder, je gebruikt ShapeStim niet, dus hoef je dat ook niet in te laden
# Esther: weer een lijntje code minder ;)
#from psychopy.visual import ShapeStim

# Esther: let er op dat ik niet weet wat de setting van Eigen Scherm Laptop zijn.
# Esther: Zie opmerking in de tekst van Class Exercises Chapter 2 daarvoor!
# ESther: verder zal de info over de grootte van je scherm ook overschreven worden door de fullscreen optie, just so you know
win=visual.Window(size=[1536, 864],color=(0,0,1),fullscr=True,monitor='Eigen Scherm Laptop')

cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
zin=visual.TextStim(win, text='Happy Halloween!',pos=(0,-0.8))
zin.draw
win.flip()
time.sleep(1)

# Esther: Vanaf hier maak je telkens opnieuw de visuele objecten aan (cirkel, ovaal1 etc.) terwijl die eigenlijk al gemaakt zijn.
# Esther: dat is niet nodig. Het volstaat om enkel de .draw() te herhalen
# Esther: weer heel wat lijnen code minder!
cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
win.flip()
time.sleep(0.5)

cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
zin=visual.TextStim(win, text='Happy Halloween!',pos=(0,-0.8))
zin.draw()
win.flip()
time.sleep(1)

cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
win.flip()
time.sleep(0.5)

cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
zin=visual.TextStim(win, text='Happy Halloween!',pos=(0,-0.8))
zin.draw()
win.flip()
time.sleep(1)

cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
win.flip()
time.sleep(0.5)

cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
zin=visual.TextStim(win, text='Happy Halloween!',pos=(0,-0.8))
zin.draw()
win.flip()
time.sleep(1)

cirkel= visual.Circle(win,radius=0.5, edges=32,color='orange')
cirkel.draw()
ovaal1= visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.2,1))
ovaal1.draw()
ovaal2=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.8,1))
ovaal2.draw()
ovaal3=visual.Circle(win,radius=0.5, edges=32,fillColor=None,size=(0.5,1))
ovaal3.draw()
ovaal4=visual.Circle(win,radius=0.5, edges=32,fillColor=None)
ovaal4.draw()
oog1=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(-0.15,0.2))
oog1.draw()
oog2=visual.Circle(win,radius=0.5, edges=32,color='black',size=(0.2,0.08),pos=(0.15,0.2))
oog2.draw()
wenkbrauw1=visual.Line(win, start=(-0.25, 0.29), end=(-0.08, 0.26),lineColor='black')
wenkbrauw1.draw()
wenkbrauw2=visual.Line(win, start=(0.25, 0.29), end=(0.08, 0.26),lineColor='black')
wenkbrauw2.draw()
neus=visual.Polygon(win, edges=3, radius=0.2,lineColor='black')
neus.draw()
mond1=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.05,-0.3),ori=180)
mond1.draw()
mond2=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.05,-0.3),ori=180)
mond2.draw()
mond3=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0.1,-0.3),ori=180)
mond3.draw()
mond4=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,-0.3),ori=180)
mond4.draw()
mond5=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(-0.1,-0.3),ori=180)
mond5.draw()
steel=visual.Polygon(win, edges=3, radius=0.08,lineColor='black',fillColor='black',pos=(0,0.53),ori=180,size=(0.2,0.4))
steel.draw()
win.flip()
time.sleep(0.5)

win.close()