from psychopy import visual

import time

from psychopy.visual import ShapeStim

win = visual.Window([500,500],color=(0,0,0))

pumpkin = visual.Circle(win, radius=0.5, edges=1000, fillColor=(1,0.278,-0.451), fillColorSpace='rgb', lineColorSpace='rgb', lineColor= (0.984,-0.373,-0.616), lineWidth=7)

steeltje = visual.Rect(win, width = 0.05, height = 0.1, pos= (0, 0.55), fillColor='green', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'green')

eye1 = visual.Circle(win, radius=0.12, edges=32, fillColor='black', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'black', pos= (0.25,0.1))
eye2 = visual.Circle(win, radius=0.12, edges=32, fillColor='black', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'black', pos= (-0.25,0.1))
glinstering_eye1 = visual.Circle(win, radius=0.04, edges=32, fillColor='white', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'white', pos= (-0.3,0.11))
glinstering_eye2 = visual.Circle(win, radius=0.04, edges=32, fillColor='white', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'white', pos= (0.2,0.11))
glinstering1 = visual.Circle(win, radius=0.02, edges=32, fillColor='white', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'white', pos= (-0.2,0.08))
glinstering2 = visual.Circle(win, radius=0.02, edges=32, fillColor='white', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'white', pos= (0.3,0.08))

neusVert = [(-0.15,-0.3),(0,-0.1),(0.15,-0.3)]
neus = ShapeStim(win, vertices= neusVert, fillColor='black', size=.5, lineColor='black')

mondVert = [(-0.4,-0.55),(0.4,-0.55)]
mond = ShapeStim(win, vertices= mondVert, fillColor='black', size=.5, lineColor='black', lineWidth=6)

wang1 = visual.Circle(win, radius=0.05, edges=32, fillColor='pink', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'pink', pos= (0.3,-0.1))
wang2 = visual.Circle(win, radius=0.05, edges=32, fillColor='pink', fillColorSpace='rgb', lineColorSpace= 'rgb', lineColor= 'pink', pos= (-0.3,-0.1))

streepje1 = visual.Rect(win, width = 0.015, height = 0.1, pos= (0,-0.28), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
streepje2 = visual.Rect(win, width = 0.015, height = 0.1, pos= (-0.15,-0.28), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
streepje3 = visual.Rect(win, width = 0.015, height = 0.1, pos= (0.15,-0.28), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
streepje4 = visual.Rect(win, width = 0.015, height = 0.1, pos= (-0.08,-0.28), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
streepje5 = visual.Rect(win, width = 0.015, height = 0.1, pos= (0.08,-0.28), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
stimWelcome = visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,0.8))

been1=visual.Rect(win, width = 0.05, height = 0.2, pos= (-0.1,-0.6), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
been2=visual.Rect(win, width = 0.05, height = 0.2, pos= (0.1,-0.6), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')

arm1=visual.Rect(win, width = 0.2, height = 0.05, pos= (-0.6,0), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
arm2=visual.Rect(win, width = 0.2, height = 0.05, pos= (0.6,0), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')

voet1=visual.Rect(win, width = 0.08, height = 0.05, pos= (-0.115,-0.7), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')
voet2=visual.Rect(win, width = 0.08, height = 0.05, pos= (0.115,-0.7), fillColor='black', fillColorSpace='rgb', lineColorSpace='rgb', lineColor= 'black')


pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
stimWelcome.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(1)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
stimWelcome.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
stimWelcome.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
stimWelcome.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
stimWelcome.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

pumpkin.draw()
steeltje.draw()
eye1.draw()
eye2.draw()
glinstering_eye1.draw()
glinstering_eye2.draw()
glinstering1.draw()
glinstering2.draw()
neus.draw()
mond.draw()
wang1.draw()
wang2.draw()
streepje1.draw()
streepje2.draw()
streepje3.draw()
streepje4.draw()
streepje5.draw()
been1.draw()
been2.draw()
arm1.draw()
arm2.draw()
voet1.draw()
voet2.draw()
win.flip()
time.sleep(0.5)

win.close()
