from psychopy import visual
import time
import turtle
win=visual.Window(size=[600,600])

# Esther: je zou alle vormen een eigen naam kunnen geven, die hier aanmaken maar zonder ze al te drawen.
# Esther: eens alles is aangemaakt, kan je de vormen tekenen en je scherm flippen.
# Esther: voor de volgende presentatie hoef je de vormen dat niet meer opnieuw aan te maken, te hoeft enkel te drawen en flippen.

#vormen aanmaken:
blaadje=visual.Polygon(win, edges=9,radius = 0.03,size=(5,2),pos = (0.18,0.55), fillColor = 'green',lineColor='green',ori=160)
pompoenlijf=visual.Circle(win,units="pix",radius=150,lineColor=[1, 0.2, -1],fillColor=[1,0.2,-1], edges=128)
oog1=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,0.2), fillColor = 'black',lineColor='black')
oog2=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,0.2), fillColor = 'black',lineColor='black')
neus=visual.Polygon(win, edges = 3,radius = .10,pos = (0,0), fillColor = 'black',lineColor='black')
steeltje=visual.Polygon(win, edges = 3,radius = .10,ori=155,pos = (0,0.58), fillColor = 'brown',lineColor='brown')
monddriehoek1=visual.Polygon(win, edges = 3,radius = .10,pos = (0,-0.2),ori=180, fillColor = 'black',lineColor='black')
monddriehoek2=visual.Polygon(win, edges = 3,radius = .10,ori=75,pos = (-0.1,-0.2),fillColor = 'black',lineColor='black')
monddriehoek3=visual.Polygon(win, edges = 3,radius = .10,pos = (0.1,-0.2),ori=285, fillColor = 'black',lineColor='black')
monddriehoek4=visual.Polygon(win, edges = 3,radius = .10,pos = (-0.2,-0.165),ori=85, fillColor = 'black',lineColor='black')
monddriehoek5=visual.Polygon(win, edges = 3,radius = .10,pos = (0.2,-0.165),ori=275, fillColor = 'black',lineColor='black')
strikjeknoop=visual.Circle(win,radius = .05,pos = (-0.3,0.42), lineColor="red",fillColor = 'red')
strikjelus1=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.24,0.5),ori=98, fillColor = 'red',lineColor='red')
strikjelus2=visual.Polygon(win, edges = 3,radius = .08,pos = (-0.36,0.34),ori=280, fillColor = 'red',lineColor='red')
TEKST=visual.TextStim(win, text = "Happy Halloween!", color = 'black', pos = (0,-0.6))

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

#Vormen tekenen en scherm flippen (met tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
TEKST.draw()
win.flip()
time.sleep(1)

#Vormen tekenen en scherm flippen (zonder tekst):
blaadje.draw()
pompoenlijf.draw()
oog1.draw()
oog2.draw()
neus.draw()
steeltje.draw()
monddriehoek1.draw()
monddriehoek2.draw()
monddriehoek3.draw()
monddriehoek4.draw()
monddriehoek5.draw()
strikjeknoop.draw()
strikjelus1.draw()
strikjelus2.draw()
win.flip()
time.sleep(0.5)

win.close()
