from psychopy import visual
import time
win=visual.Window([600,400],color=(-0.6,-0.6,-0.6),fullscr=True)
circle1= visual.Circle(win,radius = .15,pos = (0.1,0), color = 'orange',size=[1,3])
circle2= visual.Circle(win,radius = .15,pos = (-0.2,0), color = 'orange',size=[1,3])
circle3= visual.Circle(win,radius = .15,pos = (-0.1,0), color = 'orange',size=[1,3])
circle4= visual.Circle(win,radius = .15,pos = (0.2,0), color = 'orange',size=[1,3])
circle5= visual.Circle(win,radius = .15,pos = (0,0), color = 'orange',size=[1,3])
triangle1= visual.Polygon(win, edges = 3, radius =.05,pos = (0,0), color = 'yellow')
triangle2= visual.Polygon(win, edges = 3, radius =.08,pos = (-0.14,0.2), color = 'yellow')
triangle3= visual.Polygon(win, edges = 3, radius =.09,pos = (0.14,0.2), color = 'yellow')
triangle4= visual.Polygon(win, edges = 3, radius =.09,pos = (0.1,-0.25), color = 'yellow')
triangle5= visual.Polygon(win, edges = 3, radius =.09,pos = (0.04,-0.25), color = 'yellow')
triangle6= visual.Polygon(win, edges = 3, radius =.09,pos = (-0.04,-0.25), color = 'yellow')
triangle7= visual.Polygon(win, edges = 3, radius =.09,pos = (-0.1,-0.25), color = 'yellow')
# EstherL zeer leuke touch met dat hoedje!
triangle8= visual.Polygon(win, edges = 3, radius =.09,pos = (0.17,0.6), color = 'black',size=[1,3])
rectangle= visual.Rect(win, width = .05,height = .2,pos =(0,0.53),color = 'green')
rectangle1=visual.Rect(win, width = .23,height = .05,pos =(0.17,0.45),color = 'black')
stim = visual.TextStim(win, text = "Happy Halloween!", color = (1,1,1),pos=(0,-0.6))
stim.draw()
rectangle.draw()
circle1.draw()
circle2.draw()
circle3.draw()
circle4.draw()
circle5.draw()
triangle1.draw()
triangle2.draw()
triangle3.draw()
triangle4.draw()
triangle5.draw()
triangle6.draw()
triangle7.draw()
rectangle1.draw()
triangle8.draw()
win.flip()
time.sleep(1)
rectangle.draw()
circle1.draw()
circle2.draw()
circle3.draw()
circle4.draw()
circle5.draw()
triangle1.draw()
triangle2.draw()
triangle3.draw()
triangle4.draw()
triangle5.draw()
triangle6.draw()
triangle7.draw()
rectangle1.draw()
triangle8.draw()
win.flip()
time.sleep(0.5)
stim.draw()
rectangle.draw()
circle1.draw()
circle2.draw()
circle3.draw()
circle4.draw()
circle5.draw()
triangle1.draw()
triangle2.draw()
triangle3.draw()
triangle4.draw()
triangle5.draw()
triangle6.draw()
triangle7.draw()
rectangle1.draw()
triangle8.draw()
win.flip()
time.sleep(1)
rectangle.draw()
circle1.draw()
circle2.draw()
circle3.draw()
circle4.draw()
circle5.draw()
triangle1.draw()
triangle2.draw()
triangle3.draw()
triangle4.draw()
triangle5.draw()
triangle6.draw()
triangle7.draw()
rectangle1.draw()
triangle8.draw()
win.flip()
time.sleep(0.5)
stim.draw()
rectangle.draw()
circle1.draw()
circle2.draw()
circle3.draw()
circle4.draw()
circle5.draw()
triangle1.draw()
triangle2.draw()
triangle3.draw()
triangle4.draw()
triangle5.draw()
triangle6.draw()
triangle7.draw()
rectangle1.draw()
triangle8.draw()
win.flip()
time.sleep(1)
rectangle.draw()
circle1.draw()
circle2.draw()
circle3.draw()
circle4.draw()
circle5.draw()
triangle1.draw()
triangle2.draw()
triangle3.draw()
triangle4.draw()
triangle5.draw()
triangle6.draw()
triangle7.draw()
rectangle1.draw()
triangle8.draw()
win.flip()
time.sleep(0.5)
stim.draw()
rectangle.draw()
circle1.draw()
circle2.draw()
circle3.draw()
circle4.draw()
circle5.draw()
triangle1.draw()
triangle2.draw()
triangle3.draw()
triangle4.draw()
triangle5.draw()
triangle6.draw()
triangle7.draw()
rectangle1.draw()
triangle8.draw()
win.flip()
time.sleep(1)
win.close()

