from psychopy import visual
import time
win = visual.Window (color = "black", fullscr = True)
#Pompoen
tekst = visual.TextStim( win, text = "Happy Halloween!", pos = (0.73, 0.67), font = "Chiller", ori = 30, height = 0.20)
circle1 = visual.Circle(win, radius = 0.5, pos = (0, 0), fillColor = 'orange', lineColor = 'orange')
circle2 = visual.Circle (win, radius = 0.45, pos = (-0.40, 0), fillColor = 'orange', lineColor = 'orange')
circle3 = visual.Circle (win, radius = 0.45, pos = (0.40, 0), fillColor = 'orange', lineColor = 'orange')
neusVert =[(0,0.2),(-0.1, 0.1),(0.1, 0.1)]
neus = visual.ShapeStim(win, vertices = neusVert, fillColor = 'yellow', lineWidth = 0, size = 0.75)
oogrechtsVert = [(0.5, 0.5), (0.6, 0.3), (0.55, 0.3), (0.5, 0.4), (0.45, 0.3), (0.4, 0.3)]
oogrechts = visual.ShapeStim (win, vertices = oogrechtsVert, fillColor = 'yellow', lineWidth = 0, size = 0.75)
ooglinksVert = [(-0.5, 0.5), (-0.4, 0.3), (-0.45, 0.3), (-0.5, 0.4), (-0.55, 0.3), (-0.6, 0.3)]
ooglinks = visual.ShapeStim (win, vertices = ooglinksVert, fillColor = 'yellow', lineWidth = 0, size = 0.75)
mondVert = [(-0.5, -0.1), (-0.3, -0.2), (-0.25, -0.3), (-0.15, -0.3), (-0.1, -0.2), (0.1, -0.2), (0.15, -0.3), (0.25, -0.3), (0.3, -0.2), (0.5, -0.1), (0.15, -0.6), (0.1, -0.5), (-0.1, -0.5), (-0.15, -0.6)]
mond = visual.ShapeStim (win, vertices = mondVert, fillColor = 'yellow', lineWidth = 0, size = 0.60)
steelVert = [(-0.1, 0.95), (0.1, 0.95), (0.1, 0.8), (0.3, 0.7), (-0.3, 0.7), (-0.1, 0.8)]
steel = visual.ShapeStim (win, vertices = steelVert, fillColor = 'green', lineWidth = 0, size = 0.75, pos = (0,-0.075))

tekst.draw()
circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (1)

circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

tekst.draw()
circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

tekst.draw()
circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)


tekst.draw()
circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

tekst.draw()
circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

circle1.draw ()
circle2.draw ()
circle3.draw ()
neus.draw ()
oogrechts.draw ()
ooglinks.draw ()
mond.draw ()
steel.draw ()
win.flip ()
time.sleep (0.5)

win.close ()