from psychopy import visual
# Esther: waarvoor dient turtle? :)
import turtle, time
win = visual.Window(size = [800,800], color = (-0.5,-0.5,-0.5))
polygon= visual.Polygon(win, edges = 999,radius = .10,pos = (0,0), lineColor = 'black', fillColor = 'orangered', size= (8,6))
##de edges: om de cirkel smooth te maken moet je het aantal hoeken groot genoeg maken

Neus=visual.Polygon(win, edges = 3, radius = 0.10, pos = (0,-0.1),lineColor='black', fillColor= 'black')

Oog1=visual.Polygon(win, edges = 3, radius = 0.10, pos = (0.3,0.2),lineColor='black', fillColor= 'black', size = [1.1,1.5])
Oog2=visual.Polygon(win, edges = 3, radius = 0.10, pos = (-0.3,0.2),lineColor='black', fillColor= 'black', size = [1.1,1.5])

MondA = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 90, pos = (0,-0.4), lineColor= 'black', fillColor = 'black')
MondBL = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 95, pos = (-0.08,-0.38), lineColor= 'black', fillColor = 'black')
MondBR = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 85, pos = (0.08,-0.38), lineColor= 'black', fillColor = 'black')
MondCL = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 100, pos = (-0.16,-0.36), lineColor= 'black', fillColor = 'black')
MondCR = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 80, pos = (0.16,-0.36), lineColor= 'black', fillColor = 'black')
MondDL = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 105, pos = (-0.24,-0.34), lineColor= 'black', fillColor = 'black')
MondDR = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 75, pos = (0.24,-0.34), lineColor= 'black', fillColor = 'black')
MondEL = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 110, pos = (-0.32,-0.32), lineColor= 'black', fillColor = 'black')
MondER = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 70, pos = (0.32,-0.32), lineColor= 'black', fillColor = 'black')
MondFL = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 115, pos = (-0.40,-0.30), lineColor= 'black', fillColor = 'black')
MondFR = visual.Polygon(win, edges = 4, size = [1,0.6], radius = (0.1,0.1), ori = 65, pos = (0.40,-0.30), lineColor= 'black', fillColor = 'black')
HoedA = visual.Polygon(win, edges = 999, size = [1.6,0.2], ori = 10, pos = [0.1,0.5], lineColor= "black", fillColor= "black" )
HoedB = visual.Polygon(win, edges = 3, size = [0.5, 0.8], ori = 35, pos = [0.2,0.65], lineColor="black", fillColor = "black")
# Esther: blackadder :D
HappyText = visual.TextStim(win, text = "Happy Halloween!", color =[-1, -0.55, -1], font = "Blackadder ITC", pos = [0,-0.8])

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HappyText.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(1)

polygon.draw()
Neus.draw()
MondCR.draw()
Oog1.draw()
Oog2.draw()
MondA.draw()
MondBL.draw()
MondBR.draw()
MondCL.draw()
MondCR.draw()
MondDL.draw()
MondDR.draw()
MondEL.draw()
MondER.draw()
MondFL.draw()
MondFR.draw()
HoedA.draw()
HoedB.draw()

win.flip()
time.sleep(0.5)


win.close()
