from psychopy import visual
import time
win = visual.Window(fullscr = True, color= (-1,-1,-1))

# Esther: ziet er goed uit, in Chapter 3 zal je zien dat je bv. de fillColor gewoon één keer op voorhand kan aanmaken en daar in de lijnen hieronder naar verwijzen.
# Esther: hetzelfde geldt voor de size van de cirkels en de lineColor
# Esther: bijvoorbeeld:
# CircleColorRemy = (0.859,-0.027,-0.710)
# LineColorRemy = (0.827,-0.294,-0.710)
# CircleSizeRemy = (0.2,0.6)
# pompoenxxlxx = visual.Circle(win, size= CircleSizeRemy, lineWidth= 4, fillColor= CircleColorRemy, lineColor= LineColorRemy, pos= (0, 0.2))
# pompoenxlxxx = visual.Circle(win, size= CircleSizeRemy, lineWidth= 4, fillColor= CircleColorRemy, lineColor= LineColorRemy, pos= (-0.06,0.2))
# Esther: het voordeel is dat je slechts één keer de waarde hoeft aan te passen in plaats van voor elke cirkel apart ;)
# Esther: je kan dit idee ook doortrekken bij de andere vormen die hieronder aangemaakt worden.

pompoenxxlxx = visual.Circle(win, size= (0.2,0.6), lineWidth= 4, fillColor= (0.859,-0.027,-0.710), lineColor= (0.827,-0.294,-0.710), pos= (0, 0.2))
pompoenxlxxx = visual.Circle(win, size= (0.2,0.6), lineWidth= 4, fillColor= (0.859,-0.027,-0.710), lineColor= (0.827,-0.294,-0.710), pos= (-0.06,0.2))
pompoenxxxlx = visual.Circle(win, size= (0.2,0.6), lineWidth= 4, fillColor= (0.859,-0.027,-0.710), lineColor= (0.827,-0.294,-0.710), pos= (0.06,0.2))
pompoenlxxxx = visual.Circle(win, size= (0.2,0.6), lineWidth= 4, fillColor= (0.859,-0.027,-0.710), lineColor= (0.827,-0.294,-0.710), pos= (-0.12,0.2))
pompoenxxxxl = visual.Circle(win, size= (0.2,0.6), lineWidth= 4, fillColor= (0.859,-0.027,-0.710), lineColor= (0.827,-0.294,-0.710), pos= (0.12,0.2))
steeltje = visual.Rect(win, size= (0.05,0.2), fillColor = (-0.655,-0.200,-0.867), lineWidth=2, lineColor= (-0.733,-0.373,-0.875), pos= (0,0.55) )
oogL = visual.Circle(win, size= (0.04,0.05), fillColor= (1,1,1), lineColor= (-1,-1,-1), lineWidth= 50, pos= (-0.05,0.28))
oogR = visual.Circle(win, size= (0.04,0.05), fillColor= (1,1,1), lineColor= (-1,-1,-1), lineWidth= 50, pos= (0.05,0.28))
# Esther: dat was grappig!
knipoog = visual.Rect(win, size = (0.1,0.03),fillColor=(-1,-1,-1), lineColor= (-1,-1,-1), pos= (0.05,0.28))
vert =[[-1,0],[1,0],[0,4]]
neus= visual.ShapeStim(win, vertices= vert, fillColor= (-1,-1,-1), lineColor= (-1,-1,-1), size= 0.017, pos= (0,0.15))
vert2 = [[-2,1.5],[-2,1],[-1,0],[0,-0.5],[1,0],[2,1],[2,1.5],[1,0.5],[0,0],[-1,0.5],[-2,1.5]]
mond= visual.ShapeStim(win, vertices= vert2, fillColor= (-1,-1,-1), lineColor= (-1,-1,-1), size= 0.06, pos= (0,0),lineWidth= 1)
vert3= [[-0.4,0],[0.4,0], [0, -1.4]]
tandje= visual.ShapeStim(win, vertices= vert3, fillColor= (1,1,1), lineColor= (-1,-1,-1), size= 0.045, pos= (0.05,0.01),lineWidth= 3, ori= 339)
text= visual.TextStim(win, text= 'Happy Halloween!', color = (1,1,1), pos= (0,-0.5), ori= 350, bold = True, height= 0.15, font= 'Bookman Old Style')

pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
text.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
text.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
text.draw()
oogL.draw()
knipoog.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
knipoog.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
text.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.2)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
text.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
oogR.draw()
neus.draw()
text.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
win.flip()
time.sleep(0.1)
pompoenlxxxx.draw()
pompoenxxxxl.draw()
pompoenxlxxx.draw()
pompoenxxxlx.draw()
pompoenxxlxx.draw()
steeltje.draw()
oogL.draw()
oogR.draw()
neus.draw()
mond.draw()
tandje.draw()
text.draw()
win.flip()
time.sleep(3)
win.close()