from psychopy import visual, event , core
import time 
from psychopy.visual import ShapeStim

#repeat1 with text 1 sec


win = visual.Window(siz=[400,400], color=(0.961,0.961,0.863))

shadow=visual.Polygon(win, radius=0.5, size=[1,0.5],pos=(0,-0.6), edges=500, fillColor=(0.85,0.85,0.75),lineColor=(0.9,0.9,0.8), )

body = visual.Polygon(win, radius=0.5, size=[1.5,1], edges=500, fillColor='orange', fillColorSpace='rgb',lineColor='black', lineColorSpace='rgb' )

line = visual.Polygon(win, radius=0.5, size=[0.8,1],lineWidth=4, edges=500,lineColor='darkorange', lineColorSpace='rgb' )
line2 = visual.Line(win, start=(0, 0.5), end=(0, -0.5),lineWidth=3,lineColor='darkorange',lineColorSpace='rgb')
line3 = visual.Polygon(win, radius=0.5, size=[1.2,1],lineWidth=4, edges=500,lineColor='darkorange', lineColorSpace='rgb' )


steelVert = [(-0.01,0.48),(-0.04,0.5),(-0.06,0.6),(0.06,0.6),(0.04,0.5),(0.01,0.48)]
steel = ShapeStim(win, vertices=steelVert, fillColor='darkgreen',fillColorSpace='rgb', lineColor=(-1,-1,-1))

eyeL = visual.Circle(win, radius=0.1,size=[1.5,1.75], edges=32, pos=(-0.25,0.1), fillColor='black', fillColorSpace='rgb',lineColor='black', lineColorSpace='rgb' )
eyeR = visual.Circle(win, radius=0.1,size=[1.5,1.75], edges=32, pos=(0.25,0.1), fillColor='black', fillColorSpace='rgb',lineColor='black', lineColorSpace='rgb' )
pupilbigL= visual.Circle(win, radius=0.1,size=[0.75,1], edges=32, pos=(-0.275,0.15), fillColor='white', fillColorSpace='rgb',lineColor='white', lineColorSpace='rgb' )
pupiltinyL= visual.Circle(win, radius=0.1,size=[0.15,0.17], edges=32, pos=(-0.18,0.07), fillColor='white', fillColorSpace='rgb',lineColor='white', lineColorSpace='rgb' )
pupilbigR= visual.Circle(win, radius=0.1,size=[0.75,1], edges=32, pos=(0.22,0.15), fillColor='white', fillColorSpace='rgb',lineColor='white', lineColorSpace='rgb' )
pupiltinyR= visual.Circle(win, radius=0.1,size=[0.15,0.17], edges=32, pos=(0.32,0.07), fillColor='white', fillColorSpace='rgb',lineColor='white', lineColorSpace='rgb' )


mouthVert = [(-0.185,-0.2),(-0.175,-0.21),(-0.17,-0.23),(-0.165,-0.25),(-0.15,-0.26),(-0.12,-0.28),(-0.08,-0.29),(0,-0.29),(0.08,-0.29),(0.12,-0.28),(0.15,-0.26),(0.165,-0.25),(0.17,-0.23),(0.175,-0.21),(0.185,-0.2),(0.1,-0.2),(0.1,-0.24),(0.04,-0.24),(0.04,-0.2),(-0.04,-0.2),(-0.04,-0.24),(-0.1,-0.24),(-0.1,-0.2)]
mouth = ShapeStim(win, vertices=mouthVert, fillColor='black',fillColorSpace='rgb', lineColor=None)

eyebrowL= visual.TextStim(win, text = ")",pos=(-0.35,0.28),color = (-1,-1,-1), ori=55)
eyebrowR= visual.TextStim(win, text = ")",pos=(0.35,0.28),color = (-1,-1,-1), ori=110)

cheekL = visual.Circle(win, radius=0.1,size=[1,0.6], edges=32, pos=(-0.4,-0.15), fillColor='pink', fillColorSpace='rgb',lineColor='pink', lineColorSpace='rgb')
cheekR = visual.Circle(win, radius=0.1,size=[1,0.6], edges=32, pos=(0.4,-0.15), fillColor='pink', fillColorSpace='rgb',lineColor='pink', lineColorSpace='rgb' )


legL =visual.Line(win, start=(-0.15, -0.49), end=(-0.15, -0.65),lineWidth=3,lineColor=(-1,-1,-1))
legR =visual.Line(win, start=(0.15, -0.49), end=(0.15, -0.65),lineWidth=3,lineColor=(-1,-1,-1))
footL=visual.Line(win, start=(-0.145, -0.65), end=(-0.2, -0.65),lineWidth=2.5,lineColor=(-1,-1,-1))
footR=visual.Line(win, start=(0.145, -0.65), end=(0.2, -0.65),lineWidth=2.5,lineColor=(-1,-1,-1))

armL=visual.Line(win, start=(-0.73, 0.1), end=(-0.85, 0.2),lineWidth=4,lineColor=(-1,-1,-1))
armR=visual.Line(win, start=(0.73, 0.1), end=(0.85, 0.2),lineWidth=4,lineColor=(-1,-1,-1))
handL1=visual.Line(win, start=(-0.85, 0.2), end=(-0.89, 0.19),lineWidth=2,lineColor=(-1,-1,-1))
handL2=visual.Line(win, start=(-0.85, 0.2), end=(-0.89, 0.23),lineWidth=2,lineColor=(-1,-1,-1))
handL3=visual.Line(win, start=(-0.85, 0.2), end=(-0.87, 0.25),lineWidth=2,lineColor=(-1,-1,-1))
handR1=visual.Line(win, start=(0.85, 0.2), end=(0.89, 0.19),lineWidth=2,lineColor=(-1,-1,-1))
handR2=visual.Line(win, start=(0.85, 0.2), end=(0.89, 0.23),lineWidth=2,lineColor=(-1,-1,-1))
handR3=visual.Line(win, start=(0.85, 0.2), end=(0.87, 0.25),lineWidth=2,lineColor=(-1,-1,-1))

#tekst
tekst = visual.TextStim(win, text='Happy Halloween!', bold=True,font='Ink Free', height=0.15, pos=(0,0.8), color='purple', colorSpace='rgb')
tekstballon = visual.Circle(win, radius=0.1,size=[5.6,1.5], edges=32, pos=(0,0.8),lineColor='black', lineColorSpace='rgb' )
teksthoekVert = [(0.3,0.67),(0.15,0.55),(0.2,0.66)]
teksthoek = ShapeStim(win, vertices=teksthoekVert, lineColor=(-1,-1,-1))
hideline=visual.Circle(win, radius=0.1,size=[0.45,0.2], edges=32, pos=(0.245,0.67), fillColor=(0.961,0.961,0.863),lineColor=(0.961,0.961,0.863) )


#draw
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(1)

#repeat1 no text

shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

win.flip()
time.sleep(0.5)

#repeat2 text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(0.5)

#repeat3 no text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

win.flip()
time.sleep(0.5)

#repeat4 text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(0.5)

#repeat5 no text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

win.flip()
time.sleep(0.5)


#repeat6 text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(0.5)

#repeat7 no text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

win.flip()
time.sleep(0.5)

#repeat8 text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(0.5)

#repeat9 no text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

win.flip()
time.sleep(0.5)

#repeat10 text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(0.5)

#repeat11 no text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

win.flip()
time.sleep(0.5)

#repeat12 text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(0.5)

#repeat13 no text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

win.flip()
time.sleep(0.5)

#repeat14FINAL text
shadow.draw()
body.draw()
line.draw()
line2.draw()
line3.draw()
steel.draw()
eyeL.draw()
eyeR.draw()
pupilbigL.draw()
pupiltinyL.draw()
pupilbigR.draw()
pupiltinyR.draw()
mouth.draw()
eyebrowL.draw()
eyebrowR.draw()
cheekL.draw()
cheekR.draw()
legL.draw()
legR.draw()
footL.draw()
footR.draw()
armL.draw()
armR.draw()
handL1.draw()
handL2.draw()
handL3.draw()
handR1.draw()
handR2.draw()
handR3.draw()

tekst.draw()
tekstballon.draw()
teksthoek.draw()
hideline.draw()

win.flip()
time.sleep(5)






